# Generated by Django 4.1.1 on 2022-09-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
